### ISSUE TITLE
Client ID a Client Secret

### ISSUE THREAD

**Issue by danth3b0t** [TomAtomCZ/depotoPhpClient#1]
Ve formuláři na https://server1.depoto.cz/ jsou 2 hidden fieldy - `client_id` a `client_secret`. K čemu slouží?`client_secret` není moc secret, když je takhle veřejně viditelný... Musí být součástí requestu? Proč? V `Client.php` jsou taky veřejně dostupné. Není to potenciální issue?

**Comment by sajfi** [comment]
Server využívá implementuje OAuth2, z čehož vyplývá použití těchto fieldů, viz např:
https://github.com/FriendsOfSymfony/oauth2-php
